image:
  name: atlassian/default-image:2


release-dev: &release-dev
  step:
    name: Release development version
    image: python:3.7
    size: 2x
    trigger: manual
    script:
      - pip install semversioner
      - VERSION=$(semversioner current-version).${BITBUCKET_BUILD_NUMBER}-dev
      - pipe: atlassian/bitbucket-pipe-release:4.0.1
        variables:
          DOCKERHUB_USERNAME: $DOCKERHUB_USERNAME
          DOCKERHUB_PASSWORD: $DOCKERHUB_PASSWORD
          IMAGE: bitbucketpipelines/$BITBUCKET_REPO_SLUG
          GIT_PUSH: 'false'
          VERSION: ${VERSION}
    services:
      - docker


test: &test
  parallel:
    - step:
        name: Test
        image: python:3.7
        size: 2x
        script:
        - pip install -r test/requirements.txt
        - pytest test/test.py --verbose --capture=no
        - flake8 --ignore E501,E125
        services:
        - docker
    - step:
        name: Lint the Dockerfile
        image: hadolint/hadolint:latest-debian
        script:
          - hadolint Dockerfile

push: &push
  step:
    name: Push and Tag
    image: python:3.7
    size: 2x
    script:
      - pipe: atlassian/bitbucket-pipe-release:4.0.1
        variables:
          DOCKERHUB_USERNAME: $DOCKERHUB_USERNAME
          DOCKERHUB_PASSWORD: $DOCKERHUB_PASSWORD
          IMAGE: bitbucketpipelines/$BITBUCKET_REPO_SLUG
    services:
      - docker


pipelines:
  default:
  - <<: *test
  - <<: *release-dev
  branches:
    master:
    - <<: *test
    - <<: *push
