image:
  name: atlassian/default-image:2


release-canary: &release-canary
  step:
    name: Release canary version
    image: python:3.7
    script:
      - set -ex
      - pip install semversioner
      - VERSION=$(semversioner current-version)
      - IMAGE=bitbucketpipelines/$BITBUCKET_REPO_SLUG
      - echo ${DOCKERHUB_PASSWORD} | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
      - docker build -t ${IMAGE} .
      - docker tag ${IMAGE} ${IMAGE}:${VERSION}.${BITBUCKET_BUILD_NUMBER}-canary
      - docker push ${IMAGE}:${VERSION}.${BITBUCKET_BUILD_NUMBER}-canary
    services:
      - docker

release-dev: &release-dev
  step:
    name: Release development version
    image: python:3.7
    script:
      - set -ex
      - pip install semversioner
      - VERSION=$(semversioner current-version)
      - IMAGE=bitbucketpipelines/$BITBUCKET_REPO_SLUG
      - echo ${DOCKERHUB_PASSWORD} | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
      - docker build -t ${IMAGE} .
      - docker tag ${IMAGE} ${IMAGE}:${VERSION}.${BITBUCKET_BUILD_NUMBER}-dev
      - docker push ${IMAGE}:${VERSION}.${BITBUCKET_BUILD_NUMBER}-dev
    services:
      - docker

test: &test
  parallel:
    - step:
        name: Test
        image: python:3.7
        script:
        - pip install -r test/requirements.txt
        - pytest test/test.py
        - flake8 --ignore E501,E125
        services:
        - docker
    - step:
        name: Lint the Dockerfile
        image: hadolint/hadolint:latest-debian
        script:
          - hadolint Dockerfile

push: &push
  step:
    name: Push and Tag
    image: python:3.6.7
    script:
    - pip install semversioner==0.6.16
    - ./ci-scripts/bump-version.sh
    - ./ci-scripts/docker-release.sh bitbucketpipelines/$BITBUCKET_REPO_SLUG
    - ./ci-scripts/git-push.sh
    services:
    - docker


pipelines:
  default:
  - <<: *test
  - <<: *release-canary
  branches:
    master:
    - <<: *test
    - <<: *push
    develop:
    - <<: *test
    - <<: *release-dev
