image:
  name: atlassian/default-image:2


release-canary: &release-canary
  step:
    name: Release canary version
    image: python:3.7
    script:
      - set -ex
      - pip install semversioner
      - VERSION=$(semversioner current-version)
      - IMAGE=bitbucketpipelines/$BITBUCKET_REPO_SLUG
      - echo ${DOCKERHUB_PASSWORD} | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
      - docker build -t ${IMAGE} .
      - docker tag ${IMAGE} ${IMAGE}:${VERSION}.${BITBUCKET_BUILD_NUMBER}-canary
      - docker push ${IMAGE}:${VERSION}.${BITBUCKET_BUILD_NUMBER}-canary
    services:
      - docker

release-dev: &release-dev
  step:
    name: Release development version
    trigger: manual
    image: python:3.7
    script:
      - pip install semversioner
      - VERSION=$(semversioner current-version).${BITBUCKET_BUILD_NUMBER}-dev
      - pipe: docker://bitbucketpipelines/bitbucket-pipe-release:3.2.1
        variables:
          DOCKERHUB_USERNAME: $DOCKERHUB_USERNAME
          DOCKERHUB_PASSWORD: $DOCKERHUB_PASSWORD
          IMAGE: bitbucketpipelines/$BITBUCKET_REPO_SLUG
          GIT_PUSH: 'false'
          VERSION: ${VERSION}
    services:
      - docker

test: &test
  parallel:
    - step:
        name: Test
        image: python:3.7
        script:
        - pip install -r test/requirements.txt
        - pytest test/test.py --verbose --capture=no
        - flake8 --ignore E501,E125
        services:
        - docker
    - step:
        name: Lint the Dockerfile
        image: hadolint/hadolint:latest-debian
        script:
          - hadolint Dockerfile

push: &push
  step:
    name: Push and Tag
    image: python:3.6.7
    script:
    - pipe: docker://bitbucketpipelines/bitbucket-pipe-release:3.2.1
      variables:
        DOCKERHUB_USERNAME: $DOCKERHUB_USERNAME
        DOCKERHUB_PASSWORD: $DOCKERHUB_PASSWORD
        IMAGE: bitbucketpipelines/$BITBUCKET_REPO_SLUG
    services:
    - docker


pipelines:
  default:
  - <<: *test
  - <<: *release-dev
  branches:
    master:
    - <<: *test
    - <<: *push
